### ISSUE TITLE
[BUG] Failed to load LV2 plugin.

### ISSUE THREAD

**Issue by sonata-chen** [Chowdhury-DSP/ChowMatrix#24]
**Describe the bug**
LV2 plugin can't be loaded by both Ardour6 and carla. Here is the error message:
```
lilv_plugin_get_name(): warning: Plugin <file:///home/billson/.lv2/ChowMatrix.lv2/manifest.ttl> has no (mandatory) doap:name
```
**To Reproduce**
I follow your instruction written in README.md to compile the latest version.

**Screenshots**

![image](https://user-images.githubusercontent.com/59016625/103212971-42f83300-4947-11eb-950c-97dd7f68a686.png)

![image](https://user-images.githubusercontent.com/59016625/103213267-1ee92180-4948-11eb-916a-c9d11baa5f29.png)

Maybe the URI is not correct. When I try to load the plugin, this window pops up.

**Desktop (please complete the following information):**
 - OS: [Arch Linux]
 - DAW [Ardour 6.5.0, carla 2.2.0]

**The generated LV2 bundle**
**`manifest.ttl`**
``` ttl
@prefix lv2:  <http://lv2plug.in/ns/lv2core#> .
@prefix pset: <http://lv2plug.in/ns/ext/presets#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ui:   <http://lv2plug.in/ns/extensions/ui#> .

<>
    a lv2:Plugin ;
    lv2:binary <ChowMatrix.so> ;
    rdfs:seeAlso <ChowMatrix.ttl> .

<#ExternalUI>
    a <http://kxstudio.sf.net/ns/lv2ext/external-ui#Widget> ;
    ui:binary <ChowMatrix.so> ;
    lv2:requiredFeature <http://lv2plug.in/ns/ext/instance-access> ;
    lv2:optionalFeature ui:touch ;
    lv2:extensionData <http://kxstudio.sf.net/ns/lv2ext/programs#UIInterface> .

```

**`ChowMatrix.ttl`**
``` ttl
@prefix atom: <http://lv2plug.in/ns/ext/atom#> .
@prefix doap: <http://usefulinc.com/ns/doap#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix lv2:  <http://lv2plug.in/ns/lv2core#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ui:   <http://lv2plug.in/ns/extensions/ui#> .

<>
    a lv2:Plugin ;
    lv2:requiredFeature <http://lv2plug.in/ns/ext/buf-size#boundedBlockLength> ,
                        <http://lv2plug.in/ns/ext/urid#map> ;
    lv2:extensionData <http://lv2plug.in/ns/ext/options#interface> ,
                      <http://lv2plug.in/ns/ext/state#interface> ,
                      <http://kxstudio.sf.net/ns/lv2ext/programs#Interface> ;

    lv2:microVersion 0 ;
    lv2:minorVersion 3 ;


```
The angle bracket  before `a lv2:Plugin ;` is empty, is that normal?

**Comment by jatinchowdhury18** [comment]
Ah, thanks for reporting this. Unfortunately, I don't use LV2 very often, so I often rely on other more knowledgeable programmers.

That said, I think you're right that something's wrong with the `.ttl` files. For example, in the LV2 manifest for my ChowTape plugin, I see:

`CHOWTapeModel.ttl`
```
@prefix atom: <http://lv2plug.in/ns/ext/atom#> .
@prefix doap: <http://usefulinc.com/ns/doap#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix lv2:  <http://lv2plug.in/ns/lv2core#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ui:   <http://lv2plug.in/ns/extensions/ui#> .

<https://github.com/jatinchowdhury18/AnalogTapeModel>
    a lv2:Plugin ;
    lv2:requiredFeature <http://lv2plug.in/ns/ext/buf-size#boundedBlockLength> ,
                        <http://lv2plug.in/ns/ext/urid#map> ;
    lv2:extensionData <http://lv2plug.in/ns/ext/options#interface> ,
                      <http://lv2plug.in/ns/ext/state#interface> ,
                      <http://kxstudio.sf.net/ns/lv2ext/programs#Interface> ;

    ui:ui <https://github.com/jatinchowdhury18/AnalogTapeModel#ExternalUI> ,
          <https://github.com/jatinchowdhury18/AnalogTapeModel#ParentUI> ;
...
```

With that in mind, I've adjusted the way the LV2 ttl generator gets the plugin URI, and I think it should work now! If you could give it a try pulling from the [`lv2-fixes`](https://github.com/Chowdhury-DSP/ChowMatrix/tree/lv2-fixes) branch, that would be wonderful.

Thanks,
Jatin

**Comment by sonata-chen** [comment]
>If you could give it a try pulling from the lv2-fixes branch, that would be wonderful.

Ah, thanks for your quick fix. Now, the URI is correct. 
Sadly, I still can not run the plugin. No crash, but carla gets stuck and is not responding.

Any ideas?


****
![image](https://user-images.githubusercontent.com/59016625/103260320-353ebe00-49d8-11eb-8f50-6afe4267fcac.png)

**Comment by sonata-chen** [comment]
Also, I try to pass option `--config Debug` (or without any `--config` option) to cmake to get a debug build. But I still get a binary without debug info. Am i doing something wrong?

**Comment by jatinchowdhury18** [comment]
Hmmm, very strange that the Debug builds aren't working correctly... Are you able to run the plugin as a standalone app? Also, maybe @kottv has an idea?

I can take a deeper look tomorrow morning as well.

**Comment by KottV** [comment]
Hi

I  replaced juce submodule with my fork and it seems to work (and use implicit `JucePlugin_LV2URI="https://github.com/Chowdhury-DSP/ChowMatrix`". Though I haven't clear idea what is broken in Jatin's implementation.

**Comment by sonata-chen** [comment]
> Are you able to run the plugin as a standalone app? 

Yep, standalone and VST3 work pretty well.

**Comment by jatinchowdhury18** [comment]
> I  replaced juce submodule with my fork https://github.com/lv2-porting-project/JUCE/tree/cmake-playground and it seems to work (and use implicit `JucePlugin_LV2URI="https://github.com/Chowdhury-DSP/ChowMatrix`". Though I haven't clear idea what is broken in Jatin's implementation. 

Thanks Konstantin! Could you try it with my fork, but still using the `JucePlugin_LV2URI` as you defined it? (I'd try it myself but my computer is currently having battery issues 🥺).

**Comment by jatinchowdhury18** [comment]
> Also, I try to pass option `--config Debug` (or without any `--config` option) to cmake to get a debug build. But I still get a binary without debug info. Am i doing something wrong?

What version of CMake are you on? I don't think it should make a difference, but you never know...

**Comment by sonata-chen** [comment]
> What version of CMake are you on?
3.19.2

**Comment by xunil-cloud** [comment]
Maybe try this, `cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug`? Then, just run `cmake --build build`. It seems to work for me.

**Comment by sonata-chen** [comment]
> Maybe try this, cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug

Actually, you are right. It works for me too. These two method have different behaviour


- Method 1
  1. cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug
  2. cmake --build build


    This will create `Debug` folder under `build/ChowMatrix_artefact`. (or `Release` folder with `CMAKE_BUILD_TYPE` set to Release)

***

- Method 2
  1. cmake -B build
  2. cmake --build build --config Debug

    This will NOT create the `Debug` folder. Instead, anything inside the `Debug` folder will be put directly under `build/ChowMatrix_artefact`.
***


The problem is that with Method 2, I can't get a debug build. And Method 2 is provided by official [JUCE's Documentation](https://github.com/juce-framework/JUCE/blob/master/docs/CMake%20API.md), but it seems that it is not working with official JUCE repo either.

**Comment by KottV** [comment]
> > I  replaced juce submodule with my fork https://github.com/lv2-porting-project/JUCE/tree/cmake-playground and it seems to work (and use implicit `JucePlugin_LV2URI="https://github.com/Chowdhury-DSP/ChowMatrix`". Though I haven't clear idea what is broken in Jatin's implementation.
> 
> Thanks Konstantin! I ran a diff between our two versions of `JuceUtils.cmake`, and the only differences I could give were the Python TTL generator, and the LV2URI definition. Could you try it with my fork, but still using the `JucePlugin_LV2URI` as you defined it? (I'd try it myself but my computer is currently having battery issues pleading_face).

Well, result the same, hosts cannot load the plugin. I'll try to find the differences too.

**Comment by KottV** [comment]
@jatinchowdhury18
Looks that issue is in LV2 wrapper. I replaced juce_audio_plugin_client/LV2 dir with from my fork (which is old @falkTX work with JUCE6 fixes) and it does well using your JUCEUtils.cmake and this CMakeLists.txt
```
cmake_minimum_required(VERSION 3.15)
set(CMAKE_OSX_DEPLOYMENT_TARGET "10.12" CACHE STRING "Minimum OS X deployment target")
project(ChowMatrix VERSION 1.0.1)

set(CMAKE_CXX_STANDARD 17)
add_subdirectory(modules)
include_directories(modules)

# juce_set_vst2_sdk_path(C:/SDKs/VST_SDK/VST2_SDK/)

juce_add_plugin(ChowMatrix
    COMPANY_NAME chowdsp
    PLUGIN_MANUFACTURER_CODE Chow
    PLUGIN_CODE spg3
    FORMATS AU VST3 Standalone LV2 #VST
    ProductName "ChowMatrix"
    LV2_URI "https://github.com/Chowdhury-DSP/ChowMatrix")

# create JUCE header
juce_generate_juce_header(ChowMatrix)

# add sources
add_subdirectory(src)
include_directories(src)
add_subdirectory(res)

target_compile_definitions(ChowMatrix
    PUBLIC
    JUCE_DISPLAY_SPLASH_SCREEN=0
    JUCE_REPORT_APP_USAGE=0
    JUCE_WEB_BROWSER=0
    JUCE_USE_CURL=0
    JUCE_VST3_CAN_REPLACE_VST2=0

    define JucePlugin_MaxNumInputChannels=2
    define JucePlugin_MaxNumOutputChannels=2
)

target_link_libraries(ChowMatrix PUBLIC
    juce_plugin_modules
)
```

**Comment by jatinchowdhury18** [comment]
> > Maybe try this, cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug
> 
> Actually, you are right. I use cmake in a WRONG way. It has nothing to do with `ChowMatrix`. For `--config` option, it only works for Visual Studio or Xcode. (multi-configuration generators)

Ah, I had no idea! Thanks for pointing this out. Learning new things about CMake every day :). (In my typical build process, I use CMake through the VSCode cmake extension which handles most of these details for me).

**Comment by jatinchowdhury18** [comment]
> @jatinchowdhury18
> Looks that issue is in LV2 wrapper. I replaced juce_audio_plugin_client/LV2 dir with from my fork (which is old @falkTX work with JUCE6 fixes) and it does well using your JUCEUtils.cmake and this CMakeLists.txt

Okay, great! Thanks for helping to figure that out. @KottV Do you think it's worth it to try to push that version of the `juce_audio_plugin_client/LV2` code to my forked branch? That way it will be added to the Pull Request I currently have open in the DISTRHO fork. I'll see if I can add you as a collaborator on the pull request, so you can push to it directly.

**Comment by KottV** [comment]
I think it's worth if we want to make it "just work" and as a temporal solution. As upstream uses new wrapper so this problem has to be fixed in DISTRHO-JUCE.

**Comment by jatinchowdhury18** [comment]
> I think it's worth if we want to make it "just work" and as a temporal solution. As upstream uses new wrapper so this problem has to be fixed in DISTRHO-JUCE. (if i understand you correctly:))

Yeah, that's exactly what I was thinking. I tried to set it up so you can push directly to my fork, if you want to go ahead and do that, otherwise I can take a look in the morning.

**Comment by KottV** [comment]
I've got access to your branch, very appreciate this. Must say that I cannot promise to do push right now, NY is behind my door (I live in UTC +10).

**Comment by jatinchowdhury18** [comment]
@KottV, sorry I'm only getting back to this now... I've been taking a look at the different `juce_audio_plugin_client/LV2` directories between our two forks, and I've been having second thoughts about doing a simple replacement. There's a lot of differences in the code between the two forks, some of which are merely code style, but many of them seem to have functional implications, that I often don't fully understand.

With that in mind, I think it might be better for me to try to debug where the issue is happening, and try to do a more minimal fix. Ultimately, with respect to the pull request, we're talking about @falkTX's code, so he should have final say, but I think this is the route I'd like to take for now. I'll be sure to give some updates as my debugging journey progresses...

**Comment by falkTX** [comment]
well, I will keep maintaining my fork.
so feel free to use it.

as I see it, the issue here is simply the LV2 URI definition is empty.
this is a problem:
```
<>
    a lv2:Plugin ;
```
the URI is missing between the <>

**Comment by jatinchowdhury18** [comment]
@falkTX, the missing URI has been fixed with [`9383e9`](https://github.com/Chowdhury-DSP/DISTRHO-JUCE/commit/9383e9c78c7108b8b5690871d07a256e0ae20ec0) and [`0a91632`](https://github.com/Chowdhury-DSP/DISTRHO-JUCE/commit/0a916326d46b3a44bba89b0d0bf0103b8d1888a6). The issue now, is that when attempting to load the LV2 plugin in Carla, the program hangs. @sonata-chen reported this in [their reply](https://github.com/Chowdhury-DSP/ChowMatrix/issues/24#issuecomment-751952126), and I was able to confirm the same issue today in my testing.

@KottV has determined that the issue is caused by something inside the `juce_audio_plugin_client/LV2` directory. Since using the version of that directory from his fork, the issue goes away. I've been trying to pinpoint where exactly the issue is coming from within the LV2 wrapper, but none of the breakpoints that I've set are being hit. Still chipping away at it...

**Comment by KottV** [comment]
@falkTX I didn't test your fork for LV2 builds until now.
Now I've compiled https://github.com/FigBug/PAPU with your tree in "classic" manner: AppConfig.h, LV2.mak etc.
and got similar issue, jalv.gtk sees the plugin but hangs with no GUI.

```
jalv.gtk socalabs:papu
lilv_world_add_plugin(): warning: Duplicate plugin <http://yoshimi.sourceforge.net/lv2_plugin>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib64/lv2/yoshimi.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/local/lib64/lv2/yoshimi.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <http://yoshimi.sourceforge.net/lv2_plugin_multi>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib64/lv2/yoshimi.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/local/lib64/lv2/yoshimi.lv2/ (ignored)
Plugin:       socalabs:papu
UI:           socalabs:papu#ParentUI
JACK Name:    PAPU
Sample rate:  48000 Hz
Block length: 128 frames
MIDI buffers: 32768 bytes
Comm buffers: 524288 bytes
Update rate:  25,0 Hz

pulse_1_ol = 1,000000
pulse_1_or = 1,000000
pulse_1_duty = 0,000000
pulse_1_a = 0,142857
pulse_1_r = 0,142857
pulse_1_tune = 0,500000
pulse_1_tune_fine = 0,500000
pulse_1_sweep = 0,500000
pulse_1_shift = 0,000000
pulse_2_ol = 0,000000
pulse_2_or = 0,000000
pulse_2_duty = 0,000000
pulse_2_a = 0,142857
pulse_2_r = 0,142857
pulse_2_tune = 0,500000
pulse_2_tune_fine = 0,500000
noise_ol = 0,000000
noise_or = 0,000000
noise_a = 0,142857
noise_r = 0,142857
noise_shift = 0,000000
noise_step = 0,000000
noise_ratio = 0,000000
output = 1,000000
voices = 0,000000
^C^CKilled
```

working build with old LV2 wrapper:
```jalv.gtk https://socalabs.com/papu/
lilv_world_add_plugin(): warning: Duplicate plugin <http://yoshimi.sourceforge.net/lv2_plugin>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib64/lv2/yoshimi.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/local/lib64/lv2/yoshimi.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <http://yoshimi.sourceforge.net/lv2_plugin_multi>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib64/lv2/yoshimi.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/local/lib64/lv2/yoshimi.lv2/ (ignored)
Plugin:       https://socalabs.com/papu/
UI:           https://socalabs.com/papu/#ParentUI
JACK Name:    PAPU
Sample rate:  48000 Hz
Block length: 128 frames
MIDI buffers: 32768 bytes
Comm buffers: 524288 bytes
Update rate:  25,0 Hz
JUCE v6.0.5

pulse_1_ol = 1,000000
pulse_1_or = 1,000000
pulse_1_duty = 0,000000
pulse_1_a = 0,142857
pulse_1_r = 0,142857
pulse_1_tune = 0,500000
pulse_1_tune_fine = 0,500000
pulse_1_sweep = 0,500000
pulse_1_shift = 0,000000
pulse_2_ol = 0,000000
pulse_2_or = 0,000000
pulse_2_duty = 0,000000
pulse_2_a = 0,142857
pulse_2_r = 0,142857
pulse_2_tune = 0,500000
pulse_2_tune_fine = 0,500000
noise_ol = 0,000000
noise_or = 0,000000
noise_a = 0,142857
noise_r = 0,142857
noise_shift = 0,000000
noise_step = 0,000000
noise_ratio = 0,000000
output = 1,000000
voices = 0,000000
q^CExiting...
```

**Comment by KottV** [comment]
I've found a little diff in yours codes:

```
diff -u LV2_distrho/juce_LV2_Wrapper.cpp LV2_chow/juce_LV2_Wrapper.cpp
--- LV2_distrho/juce_LV2_Wrapper.cpp    2020-12-09 08:51:56.227376922 +1000
+++ LV2_chow/juce_LV2_Wrapper.cpp       2020-12-29 21:42:04.890941999 +1000
@@ -86,7 +86,7 @@
 static const String& getPluginURI()
 {
     // JucePlugin_LV2URI might be defined as a function (eg. allowing dynamic URIs based on filename)
-    static const String pluginURI(JucePlugin_LV2URI);
+    static const String pluginURI { JucePlugin_LV2URI };
     return pluginURI;
 }
 ```
 static const String pluginURI(JucePlugin_LV2URI); <-this code won't compile with cmake:
```
/home/kv/src/audio/ChowMatrix/modules/JUCE/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp:89:5: error: cannot declare static function inside another function
/home/kv/src/audio/ChowMatrix/modules/JUCE/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp:90:12: error: invalid initialization of reference of type ‘const juce::String&’ from expression of type ‘const juce::String()’
   90 |     return pluginURI;
      |            ^~~~~~~~~
```

**Comment by falkTX** [comment]
I can put ChowMatrix in DISTRHO-Ports in order to test this myself, if you do not mind.

**Comment by jatinchowdhury18** [comment]
> I can put ChowMatrix in DISTRHO-Ports in order to test this myself, if you do not mind.

Of course! Please let me know if there's any way I can assist. Thanks again to you and @KottV, for all your help :).

**Comment by jatinchowdhury18** [comment]
@sonata-chen, I've made a commit just (https://github.com/DISTRHO/JUCE/pull/13/commits/5d503f334ddb849b3e13f5d7d28e553686f44f9e), that have fixed the hanging behaviour in Carla on my testing machine. Would you be able to give it a test on your end? Again, the up-to-date changes are on [`lv2-fixes`](https://github.com/Chowdhury-DSP/ChowMatrix/tree/lv2-fixes).

Thanks,
Jatin

**Comment by sonata-chen** [comment]
Same here! It can now run on Carla and Ardour. Thanks a lot.
I hope that the [pull request](https://github.com/DISTRHO/JUCE/pull/13) will be merged soon.

**Comment by KottV** [comment]
I confirm that it works too

**Comment by falkTX** [comment]
how is that even working?

are you perhaps building with modal loops disabled?

**Comment by jatinchowdhury18** [comment]
Great to hear that it's working!

@falkTX I'm honestly not sure... From everything I can tell, it seems that `#define JUCE_MODAL_LOOPS_PERMITTED 1` is being set. Unfortunately, I don't understand `JUCE::Thread` and `JUCE::MessageManager` as well as I probably should. I did a bit more sleuthing, and it looks like JUCE has implemented their VST wrapper in the same way: https://github.com/juce-framework/JUCE/commit/d5e8c4e104a0b39625291da9d49d13e8dc5d9698.

**Comment by falkTX** [comment]
It used to work, as seen by all other code running in JUCE5 where it actually does.
So before I push such change to DISTRHO/juce I want to investigate more what is going on.

It is great to sorta know where the issue is, thanks.

**Comment by jatinchowdhury18** [comment]
Happy to help! Since everything relevant to this repo seems to be working, I'm going to merge these changes, and close this issue.

Thanks to everyone here for helping to make these LV2 builds possible!
